CREATE TABLESPACE TS_OPA
    DATAFILE 'TS_OPA.dbf'
    SIZE 7M
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 30M
    EXTENT MANAGEMENT LOCAL;
    
CREATE TEMPORARY TABLESPACE TS_OPA_TEMP
    TEMPFILE 'TS_OPA_TEMP1.dbf'
    SIZE 5M
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 20M
    EXTENT MANAGEMENT LOCAL;
    
SELECT tablespace_name FROM dba_tablespaces;

SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES FROM DBA_DATA_FILES
UNION
SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES FROM DBA_TEMP_FILES;

-- 1-3

CREATE ROLE RL_OPACORE;--alter session set "_ORACLE_SCRIPT"=true;
GRANT CONNECT TO RL_OPACORE;

GRANT CREATE SESSION, CONNECT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO RL_OPACORE;

SELECT * FROM dba_roles WHERE ROLE LIKE 'RL%';

SELECT privilege FROM dba_sys_privs WHERE grantee = 'RL_OPACORE';

COMMIT;

-- 4-5

CREATE PROFILE PF_OPACORE LIMIT 
    PASSWORD_LIFE_TIME 180 -- количество дней жизни пароля
    SESSIONS_PER_USER 3 -- количество сессий для пользователей
    FAILED_LOGIN_ATTEMPTS 7 -- количество попыток входа 
    PASSWORD_LOCK_TIME 1 -- количество дней блокирования после ошибок
    PASSWORD_REUSE_TIME 10 -- через сколько дней можно повторить пароль
    PASSWORD_GRACE_TIME DEFAULT -- количество дней предупреждений о смене пароля 
    CONNECT_TIME 180 -- время соединения, минут
    IDLE_TIME 30; -- количество минут простоя
    
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_OPACORE';

SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';

SELECT * FROM DBA_PROFILES;

-- 6-7 

CREATE USER OPACORE IDENTIFIED BY p123
DEFAULT TABLESPACE TS_OPA QUOTA UNLIMITED ON TS_OPA
TEMPORARY TABLESPACE TS_OPA_TEMP
PROFILE PF_OPACORE
ACCOUNT UNLOCK
PASSWORD EXPIRE;

GRANT RL_OPACORE TO OPACORE;

SELECT * FROM dba_users WHERE USERNAME = 'OPACORE';

-- 8


ALTER TABLESPACE TS_OPA offline;
ALTER TABLESPACE TS_OPA ONLINE;


ALTER USER OPACORE QUOTA 2M ON TS_OPA;   



