USE UNIVER;
GO
ALTER PROCEDURE PSUBJECT @P VARCHAR(20)
AS BEGIN
	SELECT * FROM SUBJECT WHERE SUBJECT = @P;
END;
GO
CREATE TABLE #SUBJECTS
(
	[SUBJECT] VARCHAR(20),
	[SUBJECT_NAME] VARCHAR(100),
	[PULPIT] VARCHAR(20)
);
GO
INSERT #SUBJECTS EXEC PSUBJECT @P = 'нно';
INSERT #SUBJECTS EXEC PSUBJECT @P = 'нюхо';

SELECT * FROM #SUBJECTS;
SELECT * FROM SUBJECT