USE UNIVER;
GO
CREATE PROCEDURE PSUBJECT
AS
BEGIN
DECLARE @K INT=(SELECT COUNT(*) FROM SUBJECT);
SELECT SUBJECT [Предметы], SUBJECT_NAME [Название_предмета], PULPIT [Кафедра] FROM SUBJECT;
RETURN @K;
END;

declare @N int =0
EXEC @N = PSUBJECT;

DECLARE @I INT=0;
EXEC @I=PSUBJECT;
PRINT 'Количество предметов: '+CAST(@I AS VARCHAR(3));

--DROP PROCEDURE PSUBJECT;