USE UNIVER;
GO

CREATE PROCEDURE PAUDITORIUM_INSERT @A CHAR(20), @N VARCHAR(50), @C INT = 0, @T CHAR(10)
AS 
 BEGIN 
   BEGIN TRY
	INSERT INTO AUDITORIUM(AUDITORIUM, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY, AUDITORIUM_NAME)
		VALUES(@A, @N, @C, @T);
	RETURN 1;
  END TRY
  BEGIN CATCH
	PRINT 'NUM: ' + CAST(ERROR_NUMBER() AS VARCHAR(6));
	PRINT 'MESSAGE: ' + ERROR_MESSAGE();
	PRINT 'SEVERITY: ' + CAST(ERROR_SEVERITY() AS VARCHAR(6));
	PRINT 'STATE: ' + CAST(ERROR_STATE() AS VARCHAR(8));
	PRINT 'ERROR LINE: ' + CAST(ERROR_LINE() AS VARCHAR(8));
	IF ERROR_PROCEDURE() IS NOT NULL   
	PRINT 'IN WHAT PROC: ' + ERROR_PROCEDURE();
	RETURN -1;
  END CATCH;
  end;
DECLARE @RC INT;  
EXEC @RC = PAUDITORIUM_INSERT @A = '30', @N = 'À ', @C = 30, @T = '10'; 
PRINT 'STATUS: ' + CAST(@RC AS VARCHAR(3));



