--alter session set "_ORACLE_SCRIPT"=true;
---------------------CREATE ROLES -------------------------------------------
CREATE ROLE RL_DEVELOPER;
CREATE ROLE RL_USER;
CREATE ROLE RL_MANAGER;
SELECT * FROM dba_roles;


GRANT UNLIMITED TABLESPACE TO RL_DEVELOPER;
SELECT *
FROM DBA_SYS_PRIVS
WHERE GRANTEE = 'RL_DEVELOPER';

---------------------ROLE DEVELOPER -------------------------------------------
GRANT   CONNECT TO RL_DEVELOPER;
GRANT    CREATE SESSION TO RL_DEVELOPER;
GRANT   CREATE ANY TABLE TO RL_DEVELOPER;
GRANT    CREATE VIEW TO RL_DEVELOPER;
GRANT    CREATE TRIGGER TO RL_DEVELOPER;
GRANT    CREATE PROCEDURE TO RL_DEVELOPER;
GRANT    CREATE TABLESPACE TO RL_DEVELOPER;
GRANT    DROP ANY TABLE TO RL_DEVELOPER;
GRANT   DROP ANY VIEW TO RL_DEVELOPER;
GRANT ALL PRIVILEGES TO RL_DEVELOPER;
GRANT EXECUTE ON UTL_I18NTO TO RL_DEVELOPER;
GRANT EXECUTE ON ENCRYPT_PASSWORD TO RL_DEVELOPER;
GRANT EXECUTE ON DECRYPT_PASSWORD TO RL_DEVELOPER;
GRANT EXECUTE ON DECRYPT_PASSWORD TO RL_DEVELOPER;
GRANT EXECUTE ON REGISTER TO RL_DEVELOPER;
GRANT EXECUTE ON LOGIN TO RL_DEVELOPER;
GRANT EXECUTE ON TOTAL_PRICE TO RL_DEVELOPER;
GRANT EXECUTE ON ADD_CAR TO RL_DEVELOPER;
GRANT EXECUTE ON INSERT_BODY_DEFAUL TO RL_DEVELOPER;
GRANT EXECUTE ON INSERT_CONDITION TO RL_DEVELOPER;
GRANT EXECUTE ON INSERT_BODY TO RL_DEVELOPER;
GRANT EXECUTE ON INSERT_PAYMENTS TO RL_DEVELOPER;
GRANT EXECUTE ON INSERT_BOOKING TO RL_DEVELOPER;
GRANT EXECUTE ON UPDATE_USER TO RL_DEVELOPER;
GRANT EXECUTE ON UPDATE_USER_PASSWORD TO RL_DEVELOPER;
GRANT EXECUTE ON UPDATE_CAR TO RL_DEVELOPER;
GRANT EXECUTE ON UPDATE_PRICING TO RL_DEVELOPER;
GRANT EXECUTE ON DELETE_USER TO RL_DEVELOPER;
GRANT EXECUTE ON DELETE_CAR TO RL_DEVELOPER;
GRANT EXECUTE ON DELETE_PAYMENT TO RL_DEVELOPER;
GRANT EXECUTE ON DELETE_BOOKING TO RL_DEVELOPER;

GRANT ALL PRIVILEGES ON USERS TO RL_DEVELOPER;
GRANT ALL PRIVILEGES ON ROLE TO RL_DEVELOPER;
GRANT ALL PRIVILEGES ON BOOKING TO RL_DEVELOPER;
GRANT ALL PRIVILEGES ON PAYMENTS TO RL_DEVELOPER;
GRANT ALL PRIVILEGES ON CARS TO RL_DEVELOPER;
GRANT ALL PRIVILEGES ON BODY TO RL_DEVELOPER;
GRANT ALL PRIVILEGES ON CONDITION TO RL_DEVELOPER;
GRANT ALL PRIVILEGES ON PRICING TO RL_DEVELOPER;

---------------------MANAGER_ROLE -------------------------------------------
GRANT   CONNECT TO RL_MANAGER;

GRANT    CREATE SESSION TO RL_MANAGER;
GRANT   CREATE ANY TABLE TO RL_MANAGER;
GRANT    CREATE VIEW TO RL_MANAGER;
GRANT    CREATE TRIGGER TO RL_MANAGER;
GRANT SELECT ANY TABLE TO RL_MANAGER;
GRANT    CREATE PROCEDURE TO RL_MANAGER;
GRANT    CREATE TABLESPACE TO RL_MANAGER;
GRANT    DROP ANY TABLE TO RL_MANAGER;
GRANT   DROP ANY VIEW TO RL_MANAGER;
GRANT   SELECT, INSERT, UPDATE ON DEV.USERS TO RL_MANAGER;
GRANT SELECT, INSERT, UPDATE ON BOOKING TO RL_MANAGER;
GRANT SELECT, INSERT, UPDATE ON PAYMENTS TO RL_MANAGER;
GRANT SELECT, INSERT, UPDATE, DELETE ON DEV.CARS TO RL_MANAGER;
GRANT SELECT, INSERT, UPDATE, DELETE ON DEV.PRICING TO RL_MANAGER;
GRANT SELECT, INSERT, UPDATE ON BODY TO RL_MANAGER;
GRANT SELECT, INSERT, UPDATE ON CONDITION TO RL_MANAGER;
GRANT EXECUTE ON REGISTER TO RL_MANAGER;
GRANT EXECUTE ON GETUSERBYID TO RL_MANAGER;
GRANT EXECUTE ON GETCARS TO RL_MANAGER;
GRANT EXECUTE ON GETBOOKINGBYUSERID TO RL_MANAGER;
GRANT EXECUTE ON SEARCH_CARS_BY_PRICE TO RL_MANAGER;
GRANT EXECUTE ON GETUSERBYID TO RL_MANAGER;
GRANT EXECUTE ON ADD_CAR TO RL_MANAGER;
GRANT EXECUTE ON GETUSERS TO RL_MANAGER;
GRANT EXECUTE ON UPDATE_CAR TO RL_MANAGER;
GRANT EXECUTE ON DELETE_CAR TO RL_MANAGER;
GRANT EXECUTE ON DELETE_PAYMENT TO RL_MANAGER;
GRANT EXECUTE ON DELETE_BOOKING TO RL_MANAGER;
GRANT EXECUTE ON DELETE_USER TO RL_MANAGER;
GRANT EXECUTE ON INSERT_BODY_DEFAULT TO RL_MANAGER;
GRANT EXECUTE ON INSERT_BOOKING TO RL_MANAGER;
GRANT EXECUTE ON INSERT_CONDITION TO RL_MANAGER;
GRANT EXECUTE ON INSERT_PAYMENTS TO RL_MANAGER;
GRANT EXECUTE ON UPDATE_CAR TO PL_MANAGER;
GRANT EXECUTE ON UPDATE_USER TO RL_MANAGER;
GRANT EXECUTE ON UPDATE_USER_PASSWORD TO RL_MANAGER;
GRANT EXECUTE ON DECTYPT_PASSWORD TO RL_MANAGER;
GRANT EXECUTE ON ENCRYPT_PASSWORD TO RL_MANAGER;
GRANT EXECUTE ON SORT_CARS_BY_CONDITION TO RL_MANAGER;

---------------------USER_ROLE -------------------------------------------
GRANT   CONNECT TO RL_USER;
GRANT    CREATE SESSION TO RL_USER;
GRANT EXECUTE ON REGISTER TO RL_USER;
GRANT EXECUTE ON LOGIN TO RL_USER;
GRANT EXECUTE ON UPDATE_USER TO RL_USER;
GRANT EXECUTE ON SORT_CARS_BY_CONDITION TO RL_USER;
GRANT EXECUTE ON UPDATE_USER_PASSWORD TO RL_USER;
GRANT EXECUTE ON GETUSERBYID TO RL_USER;
GRANT EXECUTE ON SEARCH_CARS_BY_PRICE TO RL_USER;
GRANT EXECUTE ON DELETE_BOOKING TO RL_USER;
GRANT EXECUTE ON GETCARBYID TO RL_USER;
GRANT EXECUTE ON GETCARNAMEBYPRICINGID TO RL_USER;
GRANT EXECUTE ON GETCARS TO RL_USER;
GRANT EXECUTE ON GETTOTALPRICEBYCARID TO RL_USER;
GRANT SELECT, UPDATE ON USERS TO RL_USER;
GRANT SELECT ON ROLE TO RL_USER;
GRANT SELECT ON CARS TO RL_USER;
GRANT SELECT ON PRICING TO RL_USER;
GRANT SELECT ON BODY TO RL_USER;
GRANT SELECT ON CONDITION TO RL_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON BOOKING TO RL_USER;
GRANT SELECT, INSERT, UPDATE ON PAYMENTS TO RL_USER;
REVOKE SELECT ON DEV.ALL_INFO_USER FROM RL_USER;
