CREATE USER DEV IDENTIFIED BY p123;
GRANT RL_DEVELOPER TO DEV;

CREATE USER USER_1 IDENTIFIED BY u123;
GRANT RL_USER TO USER_1;

CREATE USER MANAGER_1 IDENTIFIED BY m123;
GRANT RL_MANAGER TO MANAGER_1;

GRANT EXECUTE ON DBMS_CRYPTO TO DEV;
GRANT UNLIMITED TABLESPACE TO DEV;

GRANT EXECUTE ON DBMS_CRYPTO TO MANAGER_1;
GRANT SELECT, INSERT, UPDATE, DELETE ON DEV.USERS TO MANAGER_1;
GRANT SELECT ANY TABLE TO MANAGER_1;
GRANT UNLIMITED TABLESPACE TO MANAGER_1;

GRANT CONNECT, CREATE SESSION TO USER_1;


GRANT EXECUTE ON DEV.CALL_ADD_CAR TO MANAGER_1;