/*1-3 tasl*/

SELECT name, open_mode FROM v$pdbs

/*7 task */

ALTER USER C##OPA IDENTIFIED BY 123
ACCOUNT UNLOCK
PASSWORD EXPIRE;

GRANT CONNECT TO C##OPA;
/*8 task*/
GRANT CREATE SESSION, CONNECT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO C##OPA;
ALTER SESSION SET CONTAINER=OPA_PDB;
GRANT SYSDBA to C##OPA;
--alter session set "_ORACLE_SCRIPT"=true;


CREATE TABLESPACE TS_OPA
    DATAFILE 'TS_OPA3.dbf'
    SIZE 7M
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 20M
    EXTENT MANAGEMENT LOCAL;
    
CREATE TEMPORARY TABLESPACE TS_OPA_TEMP
    TEMPFILE 'TS_OPA_TEMP4.dbf'
    SIZE 5M
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 30M
    EXTENT MANAGEMENT LOCAL;
    
    CREATE PROFILE PF_ORACORE LIMIT 
    PASSWORD_LIFE_TIME 180 -- количество дней жизни пароля
    SESSIONS_PER_USER 3 -- количество сессий для пользователей
    FAILED_LOGIN_ATTEMPTS 7 -- количество попыток входа 
    PASSWORD_LOCK_TIME 1 -- количество дней блокирования после ошибок
    PASSWORD_REUSE_TIME 10 -- через сколько дней можно повторить пароль
    PASSWORD_GRACE_TIME DEFAULT -- количество дней предупреждений о смене пароля 
    CONNECT_TIME 180 -- время соединения, минут
    IDLE_TIME 30; -- количество минут простоя
    
    
    CREATE ROLE RL_OPACORE;
    GRANT CREATE SESSION, CONNECT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO RL_OPACORE;
    
CREATE USER C##OPA IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_OPA QUOTA UNLIMITED ON TS_OPA
TEMPORARY TABLESPACE TS_OPA_TEMP
PROFILE PF_OPACORE
ACCOUNT UNLOCK
PASSWORD EXPIRE;

GRANT RL_OPACORE TO C##OPA;

/*task 12*/

CREATE USER C##JER IDENTIFIED BY 1234567
DEFAULT TABLESPACE TS_OPA QUOTA UNLIMITED ON TS_OPA
TEMPORARY TABLESPACE TS_OPA_TEMP
PROFILE PF_OPACORE
ACCOUNT UNLOCK
PASSWORD EXPIRE;

GRANT RL_OPACORE TO C##JER;

GRANT CONNECT TO C##JER;
GRANT CREATE SESSION, CONNECT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO C##JER;
ALTER SESSION SET CONTAINER=OPA_PDB;
GRANT SYSDBA to C##JER;


/* 11 task */
SELECT object_name, object_type, owner
FROM all_objects
WHERE owner IN ('C##OPA', 'U1_OPA_PD');

/*13 task*/
SELECT sid, serial#, username, machine, program
FROM v$session
WHERE type = 'USER'
AND sid IN (
    SELECT sid
    FROM v$session
    WHERE service_name = 'opa_pdb'
);

SELECT sid, serial#, username, machine, program, con_id
FROM v$session
WHERE type = 'USER'
AND con_id = 1;
   