/* 4 task*/


CREATE TABLESPACE TS_OPA_PDB
    DATAFILE 'TS_OPA2.dbf'
    SIZE 7M
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 20M
    EXTENT MANAGEMENT LOCAL;
    
CREATE TEMPORARY TABLESPACE TS_OPA_TEMP_PDB
    TEMPFILE 'TS_OPA_TEMP3.dbf'
    SIZE 5M
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 30M
    EXTENT MANAGEMENT LOCAL;
    
    
    SELECT tablespace_name FROM dba_tablespaces;

SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES FROM DBA_DATA_FILES
UNION
SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES FROM DBA_TEMP_FILES;

CREATE ROLE RL_OPACORE_PDB;

GRANT CREATE SESSION, CONNECT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO RL_OPACORE_PDB;

SELECT * FROM dba_roles WHERE ROLE LIKE 'RL%';

SELECT privilege FROM dba_sys_privs WHERE grantee = 'RL_OPACORE_PDB';

COMMIT;

CREATE PROFILE PF_OPACORE1_PDB LIMIT 
    PASSWORD_LIFE_TIME 180 -- количество дней жизни пароля
    SESSIONS_PER_USER 3 -- количество сессий для пользователей
    FAILED_LOGIN_ATTEMPTS 7 -- количество попыток входа 
    PASSWORD_LOCK_TIME 1 -- количество дней блокирования после ошибок
    PASSWORD_REUSE_TIME 10 -- через сколько дней можно повторить пароль
    PASSWORD_GRACE_TIME DEFAULT -- количество дней предупреждений о смене пароля 
    CONNECT_TIME 180 -- время соединения, минут
    IDLE_TIME 30; -- количество минут простоя
    
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_OPACORE1_PDB';

CREATE USER U1_OPA_PDB IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_OPA_PDB QUOTA UNLIMITED ON TS_OPA_PDB
TEMPORARY TABLESPACE TS_OPA_TEMP_PDB
PROFILE PF_OPACORE_PDB
ACCOUNT UNLOCK
PASSWORD EXPIRE;

GRANT RL_OPACORE_PDB TO U1_OPA_PDB;


/* 6 task */
SELECT * FROM DBA_TABLESPACES;
SELECT * FROM DBA_ROLES;
SELECT * FROM DBA_PROFILES;
SELECT * FROM DBA_USER;
SELECT * FROM DBA_DATA_FILES;
SELECT * FROM DBA_TEMP_FILES;
SELECT GRANT, PRIVILEGE FROM DBA_SYS_PRIVS;


SELECT object_name, object_type, owner
FROM all_objects
WHERE owner IN ('U1_OPA_PD');
