/*4. Разработать сценарий, демон-стрирующий свойства навигации 
в результирующем наборе курсора с атрибутом SCROLL на примере базы данных X_UNIVER.
Использовать все известные клю-чевые слова в операторе FETCH.*/
DECLARE @TYPE NVARCHAR(20), @CAPACITY NVARCHAR(20)
DECLARE PRIMER_4 CURSOR GLOBAL STATIC SCROLL 
FOR SELECT AUDITORIUM_TYPE, AUDITORIUM_CAPACITY FROM AUDITORIUM

OPEN PRIMER_4
PRINT 'Аудитории: '
FETCH PRIMER_4 INTO @TYPE, @CAPACITY
WHILE @@FETCH_STATUS = 0
BEGIN
PRINT '' + @TYPE + ' ' + @CAPACITY
FETCH PRIMER_4 INTO @TYPE, @CAPACITY
END
CLOSE PRIMER_4

OPEN PRIMER_4
PRINT 'первая строка: '
FETCH FIRST FROM PRIMER_4 INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'третья строка от начала (ABSOLUTE)'
FETCH ABSOLUTE 3 FROM PRIMER_4 INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'третья строка от конца (ABSOLUTE)'
FETCH ABSOLUTE -3 FROM PRIMER_4 INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'пятая строка назад от текущей (RELATIVE)'
FETCH RELATIVE 5 FROM PRIMER_4 INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'вторая строка: '
FETCH NEXT FROM LOCAL INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'предыдущая строка от текущей: '
FETCH PRIOR FROM PRIMER_4 INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

PRINT 'последняя строка: '
FETCH LAST FROM PRIMER_4 INTO @TYPE, @CAPACITY
PRINT '' + @TYPE + @CAPACITY

CLOSE PRIMER_4

DEALLOCATE PRIMER_4; 