/*2. Разработать сценарий, демон-стрирующий отличие глобального курсора от локального на примере базы данных X_UNIVER.*/

USE UNIVER;
DECLARE LINESLOCAL CURSOR LOCAL FOR SELECT SUBJECT FROM SUBJECT
DECLARE @FIRST NVARCHAR(10), @ALL NVARCHAR(200) = ' ';
OPEN LINESLOCAL
FETCH LINESLOCAL INTO @FIRST
PRINT '1. ' + @FIRST
GO
DECLARE @FIRST NVARCHAR(20), @ALL NVARCHAR(300) = ' ';
FETCH LINESLOCAL INTO @FIRST --A CURSOR WITH THE NAME 'LINESLOCAL' DOES NOT EXIST.
PRINT '2. ' + @FIRST
GO  
DECLARE GLOB CURSOR GLOBAL FOR SELECT SUBJECT FROM SUBJECT
DECLARE @SUB1 NVARCHAR(20);
OPEN GLOB;
FETCH GLOB INTO @SUB1;
PRINT RTRIM(@SUB1)+' - Дисциплина';
GO
DECLARE @SUB2 NVARCHAR(20);
FETCH GLOB INTO @SUB2;
PRINT RTRIM(@SUB2)+' - Дисциплина';
GO
DECLARE @SUB3 NVARCHAR(30);
FETCH GLOB INTO @SUB3;
PRINT RTRIM(@SUB3)+' - Дисциплина';
CLOSE GLOB;

DEALLOCATE GLOB; 
go