/*3. Разработать сценарий, демон-стрирующий отличие статических курсоров от динамических на приме-ре базы данных X_UNIVER.*/

USE UNIVER
DECLARE @PUL CHAR(10), @GEN CHAR(2), @NAME CHAR(30);
DECLARE TEACHERS CURSOR LOCAL STATIC FOR SELECT PULPIT,
GENDER, TEACHER_NAME FROM TEACHER WHERE PULPIT='ИСиТ';

OPEN TEACHERS;
PRINT 'Количество строк:'+CAST(@@CURSOR_ROWS AS VARCHAR(5));
INSERT INTO TEACHER  (TEACHER,   TEACHER_NAME, GENDER, PULPIT )
VALUES ('ГРН','Гурин Николай Иванович', 'м', 'ИСиТ');
UPDATE TEACHER SET TEACHER_NAME = 'Мороз Елена Станиславовна' WHERE TEACHER = 'ГРН';
FETCH TEACHERS INTO @PUL, @GEN, @NAME;
WHILE @@FETCH_STATUS=0
BEGIN
FETCH TEACHERS INTO @PUL, @GEN, @NAME;
PRINT 'Преподаватели: '+RTRIM(@PUL)+' '+RTRIM(@GEN)+' '+RTRIM(@NAME);
END;
CLOSE TEACHERS;
DELETE TEACHER WHERE TEACHER = 'ГРН';

go
DECLARE @PUL_ CHAR(10), @GEN_ CHAR(2), @NAME_ CHAR(30);
DECLARE TEACHERS CURSOR LOCAL DYNAMIC FOR SELECT PULPIT,
GENDER, TEACHER_NAME FROM TEACHER WHERE PULPIT='ÈÑÈÒ';

OPEN TEACHERS;
PRINT 'Количество строк: '+CAST(@@CURSOR_ROWS AS VARCHAR(5));
INSERT INTO TEACHER  (TEACHER,   TEACHER_NAME, GENDER, PULPIT )
VALUES ('ГРН','Гурин Николай Иванович', 'м', 'ИСиТ');
UPDATE TEACHER SET TEACHER_NAME = 'Мороз Елена Станиславовна' WHERE TEACHER = 'ГРН';
FETCH TEACHERS INTO @PUL_, @GEN_, @NAME_;
WHILE @@FETCH_STATUS=0
BEGIN
FETCH TEACHERS INTO @PUL_, @GEN_, @NAME_;
PRINT 'Преподаватели: '+RTRIM(@PUL_)+' '+RTRIM(@GEN_)+' '+RTRIM(@NAME_);
END;
CLOSE TEACHERS;
DELETE TEACHER WHERE TEACHER = 'ГРН';