/*Разработать сценарий, демон-стрирующий свойства вло-женных транзакций, на при-мере базы данных X_UNIVER. */
USE UNIVER;

BEGIN TRAN
	INSERT AUDITORIUM_TYPE VALUES ('TEST', 'TEST TEST');
	BEGIN TRAN
		UPDATE AUDITORIUM SET AUDITORIUM = '206-1' WHERE AUDITORIUM_TYPE = 'TEST'
		COMMIT
		IF @@TRANCOUNT > 0 ROLLBACK
	SELECT
		(SELECT COUNT(*) FROM AUDITORIUM WHERE AUDITORIUM_TYPE='ЛК') 'AUDIT',
		(SELECT COUNT(*) FROM AUDITORIUM_TYPE  WHERE AUDITORIUM_TYPE='ЛК') 'TYPE'
DELETE  AUDITORIUM_TYPE WHERE  AUDITORIUM_TYPE = 'TEST'; 