USE UNIVER;
go
CREATE FUNCTION FCTEACHER(@PUL NVARCHAR(10)) RETURNS INT AS
    BEGIN
        DECLARE @COUNT INT=(SELECT COUNT(*) FROM TEACHER
        WHERE PULPIT=ISNULL(@PUL, PULPIT));
        RETURN @COUNT;
    END;
GO
-- DROP FUNCTION FCTEACHER;

-- напюыемхе й тсмйжхх:
SELECT PULPIT, DBO.FCTEACHER(PULPIT) [йнкхвеярбн опеондюбюрекеи] FROM PULPIT;

SELECT DBO.FCTEACHER(NULL) [бяецн опеондюбюрекеи];