USE UNIVER;
go

create FUNCTION TEACHER_PULPIT (@P NVARCHAR(20)) RETURNS NVARCHAR(300) AS
BEGIN
DECLARE @LIST VARCHAR(300) =' ' , @SUB VARCHAR(20);
DECLARE SUBJECT_CURSOR CURSOR LOCAL FOR
SELECT SUBJECT.SUBJECT ' ‡ÙÂ‰‡'
FROM SUBJECT
WHERE SUBJECT.PULPIT = @P
OPEN SUBJECT_CURSOR
FETCH NEXT FROM SUBJECT_CURSOR INTO @SUB
WHILE @@FETCH_STATUS = 0
BEGIN
SET @LIST=@LIST+RTRIM(@SUB)+', ';

FETCH SUBJECT_CURSOR INTO @SUB
END;
if @LIST = ' '
return -1;
RETURN @LIST;
END;
go
--+DROP FUNCTION TEACHER_PULPIT;

PRINT dbo.TEACHER_PULPIT('»—»“');
-- Œ¡–¿Ÿ≈Õ»≈   ‘”Õ ÷»»:
SELECT PULPIT ' ¿‘≈ƒ–¿', dbo.TEACHER_PULPIT(PULPIT) 'ƒ»—÷»œÀ»Õ€' FROM PULPIT;
