USE UNIVER;
go
CREATE FUNCTION COUNT_STUDENTS (@FACULTY NVARCHAR(20)) RETURNS INT AS
BEGIN

DECLARE @COUNT INT=0;
SET @COUNT=(SELECT COUNT(STUDENT.IDSTUDENT)
FROM FACULTY
INNER JOIN GROUPS ON GROUPS.FACULTY = FACULTY.FACULTY
INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
WHERE FACULTY.FACULTY = @FACULTY)
RETURN @COUNT;
END;
GO
--DROP FUNCTION COUNT_STUDENTS;

DECLARE @TEMP_1 INT = dbo.COUNT_STUDENTS('ИДиП');
PRINT 'Количество студентов ' +CAST(@TEMP_1 AS NVARCHAR(20))+ '';

SELECT FACULTY 'Факультеты',
DBO.COUNT_STUDENTS(FACULTY) 'Количество студентов'
FROM FACULTY
GO
ALTER FUNCTION COUNT_STUDENTS (@FACULTY NVARCHAR(20), @PROF NVARCHAR(20)) RETURNS INT AS
BEGIN
DECLARE @COUNT INT=0;
SET @COUNT=(SELECT COUNT(STUDENT.IDSTUDENT)
FROM FACULTY
INNER JOIN GROUPS ON GROUPS.FACULTY = FACULTY.FACULTY
INNER JOIN STUDENT ON STUDENT.IDGROUP = GROUPS.IDGROUP
WHERE FACULTY.FACULTY = @FACULTY AND GROUPS.PROFESSION = @PROF)
RETURN @COUNT;
END;
GO

DECLARE @TEMP_1 INT = DBO.COUNT_STUDENTS('ИДиП', '1-40 01 02');
PRINT 'Количество: ' + CONVERT(VARCHAR, @TEMP_1);

SELECT FACULTY.FACULTY 'Факультеты',
GROUPS.PROFESSION 'Код специальности',
DBO.COUNT_STUDENTS(FACULTY.FACULTY, GROUPS.PROFESSION) 'Количество'
FROM FACULTY
INNER JOIN GROUPS ON GROUPS.FACULTY = FACULTY.FACULTY
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION
GO