USE UNIVER
GO
INSERT INTO TEACHER(TEACHER,TEACHER_NAME,GENDER,PULPIT)
VALUES(1,2,4,4)
UPDATE TEACHER SET GENDER = '์' WHERE TEACHER='ัฬหย'

 SELECT * FROM TR_AUDIT
 SELECT *FROM TEACHER


update TEACHER set PULPIT = 'ศั่า๗' where TEACHER = 'ัฬหย'