CREATE TABLESPACE TS_OPA_PDB
    DATAFILE 'TS_OPA_PDB.dbf'
    SIZE 7M
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 20M
    EXTENT MANAGEMENT LOCAL;
    
CREATE TEMPORARY TABLESPACE TS_OPA_PDB_TEMP
    TEMPFILE 'TS_OPA_TEMP_PDB.dbf'
    SIZE 5M
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 30M
    EXTENT MANAGEMENT LOCAL;
    
    CREATE PROFILE PF_OPA_PDB LIMIT 
    PASSWORD_LIFE_TIME 180 -- количество дней жизни пароля
    SESSIONS_PER_USER 3 -- количество сессий для пользователей
    FAILED_LOGIN_ATTEMPTS 7 -- количество попыток входа 
    PASSWORD_LOCK_TIME 1 -- количество дней блокирования после ошибок
    PASSWORD_REUSE_TIME 10 -- через сколько дней можно повторить пароль
    PASSWORD_GRACE_TIME DEFAULT -- количество дней предупреждений о смене пароля 
    CONNECT_TIME 180 -- время соединения, минут
    IDLE_TIME 30; -- количество минут простоя
    
    CREATE ROLE RL_OPA_PDB;
    GRANT CREATE SESSION, CONNECT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE CLUSTER, CREATE SYNONYM, CREATE PUBLIC SYNONYM, CREATE MATERIALIZED VIEW TO RL_OPA_PDB;
    
    CREATE USER OPA IDENTIFIED BY 12345
    DEFAULT TABLESPACE TS_OPA_PDB QUOTA UNLIMITED ON TS_OPA_PDB
    TEMPORARY TABLESPACE TS_OPA_PDB_TEMP
    PROFILE PF_OPA_PDB
    ACCOUNT UNLOCK
    PASSWORD EXPIRE;

    GRANT RL_OPA_PDB TO OPA;