USE UNIVER;
GO
SELECT PULPIT.FACULTY[Факульет], TEACHER.PULPIT[Кафедра], TEACHER.TEACHER_NAME[Имя_преподавателя]
FROM TEACHER INNER JOIN PULPIT ON TEACHER.PULPIT = PULPIT.PULPIT
WHERE TEACHER.PULPIT = 'ИСиТ' FOR XML PATH, ROOT('Кафедра');