USE UNIVER;
GO
SELECT AUDITORIUM.AUDITORIUM [юсдхрнпхъ], AUDITORIUM.AUDITORIUM_TYPE [рхо],AUDITORIUM.AUDITORIUM_CAPACITY [блеярхлнярэ] 
FROM AUDITORIUM JOIN AUDITORIUM_TYPE ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE = 'кй' FOR XML AUTO, ROOT('яохянй');