USE UNIVER
GO
CREATE XML SCHEMA COLLECTION STUDENT AS 
N'<?XML VERSION="1.0" ENCODING="UTF-16" ?>
<XS:SCHEMA ATTRIBUTEFORMDEFAULT="UNQUALIFIED" 
   ELEMENTFORMDEFAULT="QUALIFIED"
   XMLNS:XS="HTTP://WWW.W3.ORG/2001/XMLSCHEMA">
<XS:ELEMENT NAME="студент">
<XS:COMPLEXTYPE><XS:SEQUENCE>
<XS:ELEMENT NAME="паспорт" MAXOCCURS="1" MINOCCURS="1">
  <XS:COMPLEXTYPE>
    <XS:ATTRIBUTE NAME="серия" TYPE="XS:STRING" USE="REQUIRED" />
    <XS:ATTRIBUTE NAME="номер" TYPE="XS:UNSIGNEDINT" USE="REQUIRED"/>
    <XS:ATTRIBUTE NAME="дата"  USE="REQUIRED">
	<XS:SIMPLETYPE>  <XS:RESTRICTION BASE ="XS:STRING">
		<XS:PATTERN VALUE="[0-9]{2}.[0-9]{2}.[0-9]{4}"/>
	 </XS:RESTRICTION> 	</XS:SIMPLETYPE>
     </XS:ATTRIBUTE>
  </XS:COMPLEXTYPE>
</XS:ELEMENT>
<XS:ELEMENT MAXOCCURS="10" NAME="телефон" TYPE="XS:STRING"/>
<XS:ELEMENT NAME="адрес">   <XS:COMPLEXTYPE><XS:SEQUENCE>
   <XS:ELEMENT NAME="страна" TYPE="XS:STRING" />
   <XS:ELEMENT NAME="город" TYPE="XS:STRING" />
   <XS:ELEMENT NAME="улица" TYPE="XS:STRING" />
   <XS:ELEMENT NAME="дом" TYPE="XS:STRING" />
   <XS:ELEMENT NAME="квартира" TYPE="XS:STRING" />
</XS:SEQUENCE></XS:COMPLEXTYPE>  </XS:ELEMENT>
</XS:SEQUENCE></XS:COMPLEXTYPE>
</XS:ELEMENT></XS:SCHEMA>';


DROP XML SCHEMA COLLECTION STUDENT;

SELECT NAME, INFO FROM STUDENT WHERE NAME='Ободов П.А';
GO
ALTER TABLE STUDENT ALTER COLUMN INFO XML;
GO
SELECT NAME, INFO FROM STUDENT;