--task1
CREATE OR REPLACE PROCEDURE GET_TEACHERS(PCODE TEACHER1.PULPIT1%TYPE) IS
BEGIN
  FOR teacher_rec IN (SELECT * FROM TEACHER1 WHERE PULPIT1 = PCODE) LOOP
    DBMS_OUTPUT.PUT_LINE('Teacher ID: ' || teacher_rec.TEACHER1  );
    DBMS_OUTPUT.PUT_LINE('Name: ' || teacher_rec.TEACHER_NAME1);
    DBMS_OUTPUT.PUT_LINE('Pulpit: ' || teacher_rec.PULPIT1);
    DBMS_OUTPUT.PUT_LINE('-------------------------');
  END LOOP;
END;

BEGIN
  GET_TEACHERS('»—Ë“');
END;

--task2
CREATE OR REPLACE FUNCTION GET_NUM_TEACHERS(P_PULPIT_CODE TEACHER1.PULPIT1%TYPE) RETURN NUMBER AS
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM TEACHER1 WHERE PULPIT1 = P_PULPIT_CODE;
  if v_count=0 or v_count is null
  then RAISE NO_DATA_FOUND;
  END IF;
  RETURN v_count;
  
  EXCEPTION
WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20001, 'Department not found: ' || P_PULPIT_CODE);
END;


DECLARE
  v_num_teachers NUMBER;
BEGIN
  v_num_teachers := GET_NUM_TEACHERS('»—Ë“');
  DBMS_OUTPUT.PUT_LINE('Number of teachers: ' || v_num_teachers);
END;

--task3
CREATE OR REPLACE PROCEDURE GET_TEACHERS (FCODE IN FACULTY1.FACULTY1%TYPE) AS
BEGIN
  FOR teacher_rec IN (SELECT TEACHER_NAME1 FROM TEACHER1 WHERE PULPIT1 IN (SELECT PULPIT1 FROM PULPIT1 WHERE FACULTY1 = FCODE)) LOOP
    DBMS_OUTPUT.PUT_LINE(teacher_rec.TEACHER_NAME1);
  END LOOP;
END;

DECLARE
  FCODE_VALUE FACULTY1.FACULTY1%TYPE := '»ƒËœ';
BEGIN
  GET_TEACHERS(FCODE_VALUE);
END;

CREATE OR REPLACE PROCEDURE GET_SUBJECTS (PCODE IN PULPIT1.PULPIT1%TYPE) AS
BEGIN
  FOR subject_rec IN (SELECT SUBJECT_NAME1 FROM SUBJECT1 WHERE PULPIT1 = PCODE) LOOP
    DBMS_OUTPUT.PUT_LINE(subject_rec.SUBJECT_NAME1);
  END LOOP;
END;

DECLARE
  PCODE_VALUE PULPIT1.PULPIT1%TYPE := '»—Ë“';
BEGIN
  GET_SUBJECTS(PCODE_VALUE);
END;

--task4

CREATE OR REPLACE FUNCTION GET_NUM_TEACHERS (FCODE IN FACULTY1.FACULTY1%TYPE) RETURN NUMBER IS
  teacher_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO teacher_count FROM TEACHER1 WHERE PULPIT1 IN (SELECT PULPIT1 FROM PULPIT1 WHERE FACULTY1 = FCODE);
  RETURN teacher_count;
END;


DECLARE
  FCODE_VALUE FACULTY1.FACULTY1%TYPE := '»ƒËœ';
  num_teachers NUMBER;
BEGIN
  num_teachers := GET_NUM_TEACHERS(FCODE_VALUE);
  DBMS_OUTPUT.PUT_LINE('Number of Teachers: ' || num_teachers);
END;

CREATE OR REPLACE FUNCTION GET_NUM_SUBJECTS (PCODE IN PULPIT1.PULPIT1%TYPE) RETURN NUMBER IS
  subject_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO subject_count FROM SUBJECT1 WHERE PULPIT1 = PCODE;
  RETURN subject_count;
END;

DECLARE
  PCODE_VALUE PULPIT1.PULPIT1%TYPE := '»—Ë“';
  num_subjects NUMBER;
BEGIN
  num_subjects := GET_NUM_SUBJECTS(PCODE_VALUE);
  DBMS_OUTPUT.PUT_LINE('Number of Subjects: ' || num_subjects);
END;


--task5


CREATE OR REPLACE PACKAGE TEACHERS IS

  PROCEDURE GET_TEACHERS (FCODE IN FACULTY1.FACULTY1%TYPE);
  
  PROCEDURE GET_SUBJECTS (PCODE IN PULPIT1.PULPIT1%TYPE);
  
  FUNCTION GET_NUM_TEACHERS (FCODE IN FACULTY1.FACULTY1%TYPE) RETURN NUMBER;
  
  FUNCTION GET_NUM_SUBJECTS (PCODE IN PULPIT1.PULPIT1%TYPE) RETURN NUMBER;

END TEACHERS;
/

CREATE OR REPLACE PACKAGE BODY TEACHERS IS

  PROCEDURE GET_TEACHERS (FCODE IN FACULTY1.FACULTY1%TYPE) AS
  BEGIN
    FOR teacher_rec IN (SELECT TEACHER_NAME1 FROM TEACHER1 WHERE PULPIT1 IN (SELECT PULPIT1 FROM PULPIT1 WHERE FACULTY1 = FCODE)) LOOP
      DBMS_OUTPUT.PUT_LINE(teacher_rec.TEACHER_NAME1);
    END LOOP;
  END;
  
  PROCEDURE GET_SUBJECTS (PCODE IN PULPIT1.PULPIT1%TYPE) AS
  BEGIN
    FOR subject_rec IN (SELECT SUBJECT_NAME1 FROM SUBJECT WHERE PULPIT1 = PCODE) LOOP
      DBMS_OUTPUT.PUT_LINE(subject_rec.SUBJECT_NAME);
    END LOOP;
  END;
  
  FUNCTION GET_NUM_TEACHERS (FCODE IN FACULTY1.FACULTY1%TYPE) RETURN NUMBER IS
    teacher_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO teacher_count FROM TEACHER1 WHERE PULPIT1 IN (SELECT PULPIT1 FROM PULPIT1 WHERE FACULTY1 = FCODE);
    RETURN teacher_count;
  END;
  
  FUNCTION GET_NUM_SUBJECTS (PCODE IN PULPIT1.PULPIT1%TYPE) RETURN NUMBER IS
    subject_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO subject_count FROM SUBJECT1 WHERE PULPIT1 = PCODE;
    RETURN subject_count;
  END;

END TEACHERS;



BEGIN
  TEACHERS.GET_TEACHERS('»ƒËœ');
   DBMS_OUTPUT.PUT_LINE('--------------------');
  TEACHERS.GET_SUBJECTS('»—Ë“');
  
  DECLARE
    num_teachers NUMBER := TEACHERS.GET_NUM_TEACHERS('»ƒËœ');
    num_subjects NUMBER := TEACHERS.GET_NUM_SUBJECTS('»—Ë“');
  BEGIN
    DBMS_OUTPUT.PUT_LINE('--------------------');
    DBMS_OUTPUT.PUT_LINE('Number of Teachers: ' || num_teachers);
      DBMS_OUTPUT.PUT_LINE('--------------------');
    DBMS_OUTPUT.PUT_LINE('Number of Subjects: ' || num_subjects);
  END;
END;