SELECT EMP_ID, PRD_TYPE_ID, year, month, sales_amount
FROM ALL_SALES
MODEL
PARTITION BY(PRD_TYPE_ID)
DIMENSION BY (EMP_ID, MONTH, YEAR)
MEASURES(AMOUNT sales_amount)
RULES (sales_amount[FOR EMP_ID FROM 21 TO 26 INCREMENT 1, FOR MONTH FROM 1 TO 12 INCREMENT 1, 2023]
= (MAX(sales_amount)[EMP_ID BETWEEN 21 AND 26, cv(), 2022] - sales_amount[cv(),cv(), 2022])/2 + sales_amount[cv(),cv(), 2022]
)
ORDER BY YEAR ASC, MONTH, EMP_ID, PRD_TYPE_ID;